name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: .
      - name: Deploy
        uses: actions/deploy-pages@v2
